export const deliverables = [
    // {   id: "",
    //     title: "",
    //     number: "",
    //     work_package: "",
    //     link: "",
    // },
    {
        id: '1',
        title: 'Report on the Conceptual formulation of logic model and methods',
        number: 'D1.1',
        work_package: '1',
        link: '',
    },
    {
        id: '2',
        title: 'Awareness in UTM operational concept',
        number: 'D5.1',
        work_package: '5',
        link: '',
    },
    {
        id: '3',
        title: 'Plan for dissemination and exploitation',
        number: 'D7.1',
        work_package: '7',
        link: '',
    },
    {
        id: '4',
        title: 'SymAware data management plan',
        number: 'D7.4',
        work_package: '7',
        link: '',
    },
    {
        id: '5',
        title: 'Public Website SymAware',
        number: 'D7.6',
        work_package: '7',
        link: '',
    },
    {
        id: '6',
        title: 'Project collaborative platform SymAware',
        number: 'D8.1',
        work_package: '8',
        link: '',
    },
    {
        id: '7',
        title: 'Ethical Requirements',
        number: 'D9.1',
        work_package: '9',
        link: '',
    },
    {
        id: '8',
        title: 'OEI Requirement No.2',
        number: 'D9.2',
        work_package: '9',
        link: '',
    },
    {
        id: '9',
        title: 'OEI Requirement No.3',
        number: 'D9.3',
        work_package: '9',
        link: '',
    },
    {
        id: '10',
        title: 'OEI Requirement No.4',
        number: 'D9.4',
        work_package: '9',
        link: '',
    },
]
