type Status = 'Pending' | 'Submitted' | 'Approved'
type DisseminationLevel = 'PU' | 'SEN'
type Type = 'R' | 'OTHER' | 'DEM' | 'ETHICS' | 'DMP' | 'DEC'

type Deliverable = {
    wp_number: string
    deliverable_related_no: string
    deliverable_no: string
    title: string
    description: string
    lead: string
    type: Type
    dissemination_level: DisseminationLevel
    due_date: string
    new_due_date: string | null
    delivery_date: string | null
    approval_date: string | null
    status: Status
    link: string
}

export const deliverables: Deliverable[] = [
    {
        wp_number: '1',
        deliverable_related_no: 'D1.1',
        deliverable_no: '1',
        title: 'Report on the Conceptual formulation of logic, model and methods',
        description:
            'Report on the Conceptual formulation of logic, model and methods for situational awareness, and their application to SymAware use cases.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2023',
        new_due_date: null,
        delivery_date: '27 Mar 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '1',
        deliverable_related_no: 'D1.2',
        deliverable_no: '2',
        title: 'First version of the framework and tool integration',
        description: 'First version of the framework and tool integration',
        lead: 'MPI-SWS',
        type: 'OTHER',
        dissemination_level: 'PU',
        due_date: '30 Sep 2023',
        new_due_date: null,
        delivery_date: '30 Sep 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '1',
        deliverable_related_no: 'D1.3',
        deliverable_no: '3',
        title: 'Second version of the framework and tool integration',
        description: 'Second version of the framework and tool integration',
        lead: 'MPI-SWS',
        type: 'OTHER',
        dissemination_level: 'PU',
        due_date: '30 Sep 2024',
        new_due_date: null,
        delivery_date: '30 Sep 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '1',
        deliverable_related_no: 'D1.4',
        deliverable_no: '4',
        title: 'Third version of the framework and tool integration',
        description:
            'Third version of the framework and tool integration accompanied by a report describing its architecture and features.',
        lead: 'MPI-SWS',
        type: 'OTHER',
        dissemination_level: 'PU',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '2',
        deliverable_related_no: 'D2.1',
        deliverable_no: '5',
        title: 'Task decomposition based on robustness metrics',
        description:
            '\u201cTask decomposition based on robustness metrics\u201d. Report methods to decompose a global task to local ones, based on quantifiable and least violating metrics.',
        lead: 'KTH',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2024',
        new_due_date: null,
        delivery_date: '30 Sep 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '2',
        deliverable_related_no: 'D2.2',
        deliverable_no: '6',
        title: 'Explainability mechanisms',
        description:
            '\u201cExplainability mechanisms\u201d. Report describing developed mechanisms for explainability.',
        lead: 'UU',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '2',
        deliverable_related_no: 'D2.3',
        deliverable_no: '7',
        title: 'Task planning for a multi-agent system based on risk awareness',
        description:
            '\u201cTask planning for a multi-agent system based on risk awareness\u201d Report decentralized decision making algorithms to reduce the quantified associated risks.',
        lead: 'KTH',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2025',
        new_due_date: null,
        delivery_date: '31 Mar 2025',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '2',
        deliverable_related_no: 'D2.4',
        deliverable_no: '8',
        title: 'Task planning using limited information',
        description:
            '\u201cTask planning using limited information\u201d Report abstraction-based approaches to address the formal specifications using partial knowledge from the agent\u2019s objectives/tasks.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2024',
        new_due_date: null,
        delivery_date: '30 Sep 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '2',
        deliverable_related_no: 'D2.5',
        deliverable_no: '9',
        title: 'Adaptability of the multi-agent performance with respect to task/structural changes',
        description:
            '\u201cAdaptability of the multi-agent performance to tasks/structural changes\u201d Report task replanning methods with respect to/by group reconfiguration in a least violating setting.',
        lead: 'KTH',
        type: 'R',
        dissemination_level: 'PU',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '3',
        deliverable_related_no: 'D3.1',
        deliverable_no: '10',
        title: 'Local risk measures for multi-agent systems',
        description:
            '\u201cLocal risk measures for multi-agent systems\u201d. Report describing local risk measures that can be used for risk-aware multi-agent planning and how they can be computed.',
        lead: 'TUE',
        type: 'R',
        dissemination_level: 'PU',
        due_date: '30 Sep 2025',
        new_due_date: null,
        delivery_date: '02 Oct 2025',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '3',
        deliverable_related_no: 'D3.2',
        deliverable_no: '11',
        title: 'Mechanisms to communicate risk',
        description:
            '\u201cMechanisms to communicate risk\u201d. Report describing results from user studies on the mechanisms to effectively communicate risk.',
        lead: 'UU',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Nov 2025',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '3',
        deliverable_related_no: 'D3.3',
        deliverable_no: '12',
        title: 'Methods to predict and quantify uncertain scenarios',
        description:
            '\u201cMethods to predict and quantify uncertain scenarios\u201d Report describing the obtained methods and algorithms which yield quantifiable coverage over all feasible scenarios.',
        lead: 'TUE',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2024',
        new_due_date: null,
        delivery_date: '31 Mar 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '3',
        deliverable_related_no: 'D3.4',
        deliverable_no: '13',
        title: 'Risk based on the unknown unsafe scenarios',
        description:
            '\u201cRisk based on the unknown unsafe scenarios\u201d Report describing the obtained methods to find new unsafe scenarios based on real-time knowledge.',
        lead: 'SISW',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2025',
        new_due_date: null,
        delivery_date: '24 Sep 2025',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '4',
        deliverable_related_no: 'D4.1',
        deliverable_no: '14',
        title: 'An automated methodology for verifying knowledge awareness',
        description:
            '\u201cAn automated methodology for verifying knowledge awareness\u201d. Report describing the results on symbolic computational algorithms for checking the formal statements on awareness under the dynamics of the agents and with learning-enabled agents.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2024',
        new_due_date: null,
        delivery_date: '29 Mar 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '4',
        deliverable_related_no: 'D4.2',
        deliverable_no: '15',
        title: 'Verification of knowledge awareness for learning-enabled agents',
        description:
            '\u201cverification of knowledge awareness for learning-enabled agents\u201d. Report on symbolic computational algorithms for knowledge awareness in learning-enabled agents.',
        lead: 'UU',
        type: 'R',
        dissemination_level: 'PU',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '4',
        deliverable_related_no: 'D4.3',
        deliverable_no: '16',
        title: 'Communicating spatial information to humans',
        description:
            '\u201cCommunicating spatial information to humans\u201d. Report describing results from user studies on the mechanisms to provide spatial information to humans.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '5',
        deliverable_related_no: 'D5.1',
        deliverable_no: '17',
        title: 'Awareness in UTM operational concept',
        description:
            '\u201cAwareness in UTM operational concept\u201d. Report describing UTM operational concept based on concepts and initial awareness models.',
        lead: 'NLR',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 May 2023',
        new_due_date: null,
        delivery_date: '30 May 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '5',
        deliverable_related_no: 'D5.2',
        deliverable_no: '18',
        title: 'Extensive awareness models for safe and resilient UTM',
        description:
            '\u201cExtensive awareness models for safe and resilient UTM\u201d. Report describing all awareness models for UTM operations, including normal operating conditions and failure conditions.',
        lead: 'NLR',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2024',
        new_due_date: null,
        delivery_date: '30 Sep 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '5',
        deliverable_related_no: 'D5.3',
        deliverable_no: '19',
        title: 'Safety and resilience impact of aware UTM',
        description:
            '\u201cSafety and resilience impact of aware UTM\u201d. Report describing safety and resilience results of simulated UTM operations with various types of disturbances affecting the operations and for various types of awareness strategies in the UTM operations.',
        lead: 'NLR',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '5',
        deliverable_related_no: 'D5.4',
        deliverable_no: '20',
        title: 'Vehicle-in-the-loop demonstrator',
        description:
            '\u201cVehicle in the loop demonstrator\u201d. Building a VIL environment to demonstrate application of the awareness framework for verification and validation of automated driving functionalities.',
        lead: 'SISW',
        type: 'DEM',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2024',
        new_due_date: null,
        delivery_date: '30 Sep 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '5',
        deliverable_related_no: 'D5.5',
        deliverable_no: '21',
        title: 'Analysis of awareness in different unknown-unsafe scenarios',
        description:
            '\u201cAnalysis of awareness in different unknown-unsafe scenarios\u201d. Report describing effectiveness of the developed awareness in improvement of automated driving vehicles.',
        lead: 'SISW',
        type: 'R',
        dissemination_level: 'PU',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '6',
        deliverable_related_no: 'D6.1',
        deliverable_no: '22',
        title: 'Ethical issues in human-agent interaction',
        description:
            '\u201cEthical issues in human-agent interaction\u201d. Report describing the ethical issues identified in studies with end users in the use cases.',
        lead: 'UU',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2024',
        new_due_date: null,
        delivery_date: '30 Sep 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '6',
        deliverable_related_no: 'D6.2',
        deliverable_no: '23',
        title: 'Safety and risk in human-agent interaction',
        description:
            '\u201cSafety and risk in human-agent interaction\u201d. Report describing the investigation of different classes of risk in human-agent interaction and the implications for safety.',
        lead: 'TUE',
        type: 'R',
        dissemination_level: 'PU',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '6',
        deliverable_related_no: 'D6.3',
        deliverable_no: '24',
        title: 'Mechanisms for fairness in situational awareness technologies',
        description:
            '\u201cMechanisms for fairness in situational awareness technologies\u201d. Report describing mechanisms to promote fairness in situational awareness technologies.',
        lead: 'UU',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.1',
        deliverable_no: '25',
        title: 'Plan for Dissemination and Exploitation Including Communication Activities (1st version)',
        description:
            '\u201cPlan for Dissemination and Exploitation Including Communication Activities (1st version)\u201d',
        lead: 'KTH',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2023',
        new_due_date: null,
        delivery_date: '31 Mar 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.2',
        deliverable_no: '26',
        title: 'Report for Dissemination and Exploitation RP1',
        description:
            '"Report for Dissemination and Exploitation activities RP1"',
        lead: 'KTH',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2023',
        new_due_date: null,
        delivery_date: '29 Sep 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.3',
        deliverable_no: '27',
        title: 'Plan for Dissemination and Exploitation Including Communication Activities (final version)',
        description:
            '"Plan for Dissemination and Exploitation Including Communication Activities (final version)"',
        lead: 'KTH',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.4',
        deliverable_no: '28',
        title: 'Data Management Plan (1st version)',
        description: '\u201cData Management Plan (first version)\u201d.',
        lead: 'TUE',
        type: 'DMP',
        dissemination_level: 'PU',
        due_date: '31 Mar 2023',
        new_due_date: null,
        delivery_date: '31 Mar 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.5',
        deliverable_no: '29',
        title: 'Data Management Plan (final version)',
        description: '\u201cData Management Plan (final version)\u201d.',
        lead: 'TUE',
        type: 'DMP',
        dissemination_level: 'PU',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.6',
        deliverable_no: '30',
        title: 'Public website',
        description:
            '\u201cPublic website\u201d, Design and first implementation with core (static) content.',
        lead: 'MPI-SWS',
        type: 'DEC',
        dissemination_level: 'PU',
        due_date: '31 Dec 2022',
        new_due_date: null,
        delivery_date: '29 Mar 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.7',
        deliverable_no: '31',
        title: 'Software tools on public Git repository (first release)',
        description:
            '\u201cSoftware tools on public Git repository (first release)\u201d.',
        lead: 'MPI-SWS',
        type: 'OTHER',
        dissemination_level: 'PU',
        due_date: '30 Sep 2023',
        new_due_date: null,
        delivery_date: '27 Sep 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.8',
        deliverable_no: '32',
        title: 'Software tools on public Git repository (second release)',
        description:
            '\u201cSoftware tools on public Git repository (second release)\u201d.',
        lead: 'MPI-SWS',
        type: 'OTHER',
        dissemination_level: 'PU',
        due_date: '30 Sep 2024',
        new_due_date: null,
        delivery_date: '30 Sep 2024',
        approval_date: null,
        status: 'Submitted',
        link: '',
    },
    {
        wp_number: '7',
        deliverable_related_no: 'D7.9',
        deliverable_no: '33',
        title: 'Software tools on public Git repository (third release)',
        description:
            '\u201cSoftware tools on public Git repository (third release)\u201d.',
        lead: 'MPI-SWS',
        type: 'OTHER',
        dissemination_level: 'PU',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '8',
        deliverable_related_no: 'D8.1',
        deliverable_no: '34',
        title: 'Project collaborative platform',
        description:
            'Project collaborative platform. Platform for sharing project documents (reports, meeting minutes, other information) including document templates for Deliverable reports, presentation slides etc.',
        lead: 'MPI-SWS',
        type: 'OTHER',
        dissemination_level: 'SEN',
        due_date: '31 Oct 2022',
        new_due_date: null,
        delivery_date: '29 Mar 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '8',
        deliverable_related_no: 'D8.2',
        deliverable_no: '35',
        title: 'Technical/scientific review meeting documents 1',
        description:
            'A report including (i) the draft agenda, (ii) list of participants and (iii) presentations to be delivered during the review meeting.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Oct 2023',
        new_due_date: null,
        delivery_date: '03 Nov 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '8',
        deliverable_related_no: 'D8.3',
        deliverable_no: '36',
        title: 'Technical/scientific review meeting documents 2',
        description:
            'A report including (i) the draft agenda, (ii) list of participants and (iii) presentations to be delivered during the review meeting.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '9',
        deliverable_related_no: 'D9.1',
        deliverable_no: '37',
        title: 'AI - Requirement No. 1',
        description:
            '- The applicant must provide details on how external auditability of decision processes will be ensured (regarding that AI systems should have functionality to enable external human agencies to audit the communications, decision processes and other aspects relevant to AI interactions and behaviour). Design should include provision for preserving all data in case of accident and/or fundamental device failure.\n\n- A detailed explanation on the measures taken to prevent, avoid and mitigate potential bias, discrimination and stigmatisation in input data and algorithm design and outcomes must be submitted as a deliverable before the start of the relevant activities.\n\n- A detailed explanation on how the research participants and/or end-users will be informed about: (1) their interaction with an AI system/technology; (2) the abilities, limitations, risks and benefits of the AI system/technique; (3) the manner in which decisions are taken and the logic behind them must be submitted as a deliverable before the start of the relevant activities.\n\n- A detailed explanation on how humans will maintain meaningful control over the most important aspects of decision-making process (please specify) must be submitted as a deliverable before the start of the relevant activities.',
        lead: 'MPI-SWS',
        type: 'ETHICS',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2023',
        new_due_date: null,
        delivery_date: '31 Mar 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '9',
        deliverable_related_no: 'D9.2',
        deliverable_no: '38',
        title: 'OEI - Requirement No. 2',
        description:
            '- Risk assessment and details on measures to prevent misuse of research findings must be submitted as a deliverable before the start of the relevant activities.',
        lead: 'MPI-SWS',
        type: 'ETHICS',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2023',
        new_due_date: null,
        delivery_date: '30 Jun 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '9',
        deliverable_related_no: 'D9.3',
        deliverable_no: '39',
        title: 'OEI - Requirement No. 3',
        description:
            'The consortium must appoint an independent Ethics Advisor at the beginning of the project to advise the consortium on how to address the ethics issues raised. The deliverable must contain the CV of the independent Ethics Advisor selected, and their nomination.',
        lead: 'MPI-SWS',
        type: 'ETHICS',
        dissemination_level: 'SEN',
        due_date: '31 Oct 2022',
        new_due_date: null,
        delivery_date: '31 Mar 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '9',
        deliverable_related_no: 'D9.4',
        deliverable_no: '42',
        title: 'OEI - Requirement No. 4',
        description:
            'An interim ethics report on how the ethics issues in the project will be addressed.',
        lead: 'MPI-SWS',
        type: 'ETHICS',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2023',
        new_due_date: null,
        delivery_date: '30 Jun 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '9',
        deliverable_related_no: 'D9.5',
        deliverable_no: '43',
        title: 'OEI - Requirement No. 5',
        description:
            'An ethics report on how the ethics issues in the project have been addressed during the 1st Reporting Period.',
        lead: 'MPI-SWS',
        type: 'ETHICS',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2023',
        new_due_date: null,
        delivery_date: '25 Sep 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '9',
        deliverable_related_no: 'D9.6',
        deliverable_no: '44',
        title: 'OEI - Requirement No. 6',
        description:
            'An ethics report on how the ethics issues in the project have been addressed in the 2nd Reporting Period.',
        lead: 'MPI-SWS',
        type: 'ETHICS',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2025',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
    {
        wp_number: '10',
        deliverable_related_no: 'D10.1',
        deliverable_no: '40',
        title: 'Portfolio Activities Report No. 1',
        description:
            'Report on Portfolio activities. The report will present the collaboration activities that have been carried out in each reporting period and contain relevant materials (e.g., power point presentations, minutes of the meetings, etc.). It also explains how the Portfolio activities and the EIC proactive project management approach contribute to the achievement of the project objectives and help the transition to market.\nA report will be submitted at the end of each reporting period.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '30 Sep 2023',
        new_due_date: null,
        delivery_date: '27 Sep 2023',
        approval_date: '19 Feb 2024',
        status: 'Approved',
        link: '',
    },
    {
        wp_number: '10',
        deliverable_related_no: 'D10.2',
        deliverable_no: '41',
        title: 'Portfolio Activities Report No. 2',
        description:
            'Report on Portfolio activities. The report will present the collaboration activities that have been carried out in each reporting period and contain relevant materials (e.g., power point presentations, minutes of the meetings, etc.). It also explains how the Portfolio activities and the EIC proactive project management approach contribute to the achievement of the project objectives and help the transition to market.\nA report will be submitted at the end of each reporting period.',
        lead: 'MPI-SWS',
        type: 'R',
        dissemination_level: 'SEN',
        due_date: '31 Mar 2026',
        new_due_date: null,
        delivery_date: null,
        approval_date: null,
        status: 'Pending',
        link: '',
    },
]
