export const deliverables = [
    // {   id: "",
    //     title: "",
    //     number: "",
    //     work_package: "",
    //     link: "",
    // },
    {
        id: '1',
        title: 'Report on the Conceptual formulation of logic model and methods',
        number: 'D1.1',
        work_package: '1',
        link: '',
        due: '31 Mar 2023',
        submitted: '27 Mar 2023',
    },
    {
        id: '2',
        title: 'First version of the framework and tool integration',
        number: 'D1.2',
        work_package: '1',
        link: '',
        due: '30 Sep 2023',
        submitted: '30 Sep 2023',
    },
    {
        id: '3',
        title: 'Awareness in UTM operational concept',
        number: 'D5.1',
        work_package: '5',
        link: '../../assets/deliverables/D5.1_Awareness_in_UTM_operational_concept.pdf',
        due: '31 May 2023',
        submitted: '30 May 2023',
    },
    {
        id: '4',
        title: 'Plan for Dissemination and Exploitation Including Communication Activities (1st version)',
        number: 'D7.1',
        work_package: '7',
        link: '',
        due: '31 Mar 2023',
        submitted: '31 Mar 2023',
    },
    {
        id: '5',
        title: 'Report for Dissemination and Exploitation RP1',
        number: 'D7.2',
        work_package: '7',
        link: '',
        due: '30 Sep 2023',
        submitted: '29 Sep 2023',
    },
    {
        id: '6',
        title: 'Data Management Plan (1st version)',
        number: 'D7.4',
        work_package: '7',
        link: '',
        due: '31 Mar 2023',
        submitted: '31 Mar 2023',
    },
    {
        id: '7',
        title: 'Public Website',
        number: 'D7.6',
        work_package: '7',
        link: '',
        due: '31 Dec 2022',
        submitted: '29 Mar 2023',
    },
    {
        id: '8',
        title: 'Software tools on public Git repository (first release)',
        number: 'D7.7',
        work_package: '7',
        link: '',
        due: '30 Sep 2023',
        submitted: '27 Sep 2023',
    },
    {
        id: '9',
        title: 'Project collaborative platform',
        number: 'D8.1',
        work_package: '8',
        link: '',
        due: '31 Oct 2022',
        submitted: '29 Mar 2023',
    },
    // {
    //     id: '7',
    //     title: 'Technical/scientific review meeting documents 1',
    //     number: 'D8.2',
    //     work_package: '8',
    //     link: '',
    //     due: '31 Oct 2023',
    //     submitted: '',
    // },
    {
        id: '10',
        title: 'AI - Requirement No. 1',
        number: 'D9.1',
        work_package: '9',
        link: '',
        due: '31 Mar 2023',
        submitted: '31 Mar 2023',
    },
    {
        id: '11',
        title: 'OEI Requirement No.2',
        number: 'D9.2',
        work_package: '9',
        link: '',
        due: '31 Mar 2023',
        submitted: '30 Jun 2023',
    },
    {
        id: '12',
        title: 'OEI Requirement No.3',
        number: 'D9.3',
        work_package: '9',
        link: '',
        due: '31 Oct 2022',
        submitted: '31 Mar 2023',
    },
    {
        id: '13',
        title: 'OEI Requirement No.4',
        number: 'D9.4',
        work_package: '9',
        link: '',
        due: '31 Mar 2023',
        submitted: '30 Jun 2023',
    },
    {
        id: '14',
        title: 'OEI Requirement No.5',
        number: 'D9.5',
        work_package: '9',
        link: '',
        due: '30 Sep 2023',
        submitted: '25 Sep 2023',
    },
    {
        id: '15',
        title: 'Portfolio Activities Report No. 1',
        number: 'D10.1',
        work_package: '10',
        link: '',
        due: '30 Sep 2023',
        submitted: '27 Sep 2023',
    },
    // New
    {
        id: '16',
        title: 'Second version of the framework and tool integration',
        number: 'D1.3',
        work_package: '1',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
    {
        id: '16',
        title: 'Second version of the framework and tool integration',
        number: 'D1.3',
        work_package: '1',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
    {
        id: '17',
        title: 'Software tools on public Git repository (second release)',
        number: 'D7.8',
        work_package: '7',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
    {
        id: '18',
        title: 'Task planning using limited information',
        number: 'D2.4',
        work_package: '2',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
    {
        id: '19',
        title: 'Task decomposition based on robustness metrics',
        number: 'D2.1',
        work_package: '2',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
    {
        id: '20',
        title: 'Ethical issues in human-agent interaction',
        number: 'D6.1',
        work_package: '6',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
    {
        id: '21',
        title: 'Extensive awareness models for safe and resilient UTM',
        number: 'D5.2',
        work_package: '5',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
    {
        id: '22',
        title: 'Vehicle-in-the-loop demonstrator',
        number: 'D5.4',
        work_package: '5',
        link: '',
        due: '30 Sep 2024',
        submitted: '27 Sep 2024',
    },
]
