type Year = '2022' | '2023' | '2024' | '2025'
type EuPlatform = 'Yes' | 'No' | 'In review' | null
type Status =
    | 'Published'
    | 'In review'
    | 'Accepted'
    | 'Accepted/Presented'
    | 'Submitted'
    | null
type TypePidRepo = 'DOI' | 'arxiv link' | 'Researchgate link' | null
type TypePub =
    | 'Publication in conference proceeding/workshop'
    | 'Article in Journal'
    | 'Chapter in Journal'
    | null

type Publication = {
    date: string
    status: Status
    eu_platform: EuPlatform
    type_pid_repo: TypePidRepo
    pid: string
    pid_pub: string | null
    type_pub: TypePub
    link: string
    title: string
    authors: string
    journal: string
    number: string | number | null
    issn: string
    publisher: string
    month: string
    year: Year
    open_access: boolean | null
    peer_reviewed: boolean | null
    pid_book: string | null
    book_title: string | null
    oa_fees: string | null
    apc_charged: boolean | null
    consortium_partner: string
    topic: string | null
    data_used: string | null
    data_zenodo: string | null
    doi: string
}

export const publications = [
    {
        date: '2023-08-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'Yes',
        type_pid_repo: 'DOI',
        pid: '10.48550/arXiv.2203.10041',
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2203.10041',
        title: 'Compositional Synthesis of Signal Temporal Logic Tasks via Assume-Guarantee Contracts',
        authors:
            'Siyuan Liu, Adnane Saoud, Pushpak Jagtap, Dimos V. Dimarogonas, Majid Zamani',
        journal: '2022 IEEE 61st Conference on Decision and Control (CDC',
        number: null,
        issn: '2576-2370',
        publisher: 'IEEE',
        month: 'March',
        year: '2022',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc51059.2022.9992715',
    },
    {
        date: '2023-08-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'Yes',
        type_pid_repo: 'DOI',
        pid: null,
        pid_pub: '10.48550/arXiv.2210.08269',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2210.08269',
        title: 'Correct-by-Design Control of Parametric Stochastic Systems',
        authors:
            'Oliver Sch\u00f6n, Birgit van Huijgevoort, Sofie Haesaert, Sadegh Soudjani',
        journal:
            '2022 IEEE 61st Conference on Decision and Control (CDC), 2022',
        number: null,
        issn: '2576-2370 ',
        publisher: 'IEEE',
        month: 'October',
        year: '2022',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'Max Plank, Newcastle University, TU/e',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc51059.2022.9992723',
    },
    {
        date: '2023-08-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'Yes',
        type_pid_repo: 'DOI',
        pid: '10.1145/3575870.3587123',
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://dl.acm.org/doi/abs/10.1145/3575870.3587123',
        title: 'SySCoRe: Synthesis via Stochastic Coupling Relations',
        authors:
            'Birgit van Huijgevoort, Oliver Sch\u00f6n, Sadegh Soudjani, Sofie Haesaert',
        journal:
            "HSCC '23: Proceedings of the 26th ACM International Conference on Hybrid Systems: Computation and Control",
        number: null,
        issn: '9798400700330',
        publisher:
            'Association for Computing Machinery  New York, NY, United States',
        month: 'May',
        year: '2023',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'Max Plank, Newcastle University, TU/e',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1145/3575870.3587123',
    },
    {
        date: '2023-08-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'Yes',
        type_pid_repo: 'DOI',
        pid: '10.1145/3575870.3589554',
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://dl.acm.org/doi/abs/10.1145/3575870.3589554',
        title: 'Poster Abstract: A Toolchain for Accelerated Symbolic Control',
        authors:
            'Rupak Majumdar, Kaushik Mallik, Mateusz Rychlicki, Anne-Kathrin Schmuck, Sadegh Soudjani',
        journal:
            "HSCC '23: Proceedings of the 26th ACM International Conference on Hybrid Systems: Computation and Control",
        number: null,
        issn: '',
        publisher: null,
        month: 'May',
        year: '2023',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: null,
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1145/3575870.3589554',
    },
    {
        date: '2023-08-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'Yes',
        type_pid_repo: 'DOI',
        pid: '10.3389/fcomp.2023.1152532',
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: 'https://www.frontiersin.org/articles/10.3389/fcomp.2023.1152532/full',
        title: 'A case study in designing trustworthy interactions: implications for socially assistive robotics',
        authors: 'Mengyu Zhong, Marc Fraile, Ginevra Castellano, Katie Winkle',
        journal: 'Frontiers in Computer Science',
        number: 'Volume 5, 2023',
        issn: '2624-9898',
        publisher: 'Frontiers Media',
        month: 'June',
        year: '2023',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'Uppsala University',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.3389/fcomp.2023.1152532',
    },
    {
        date: '2023-08-11T00:00:00.000',
        status: 'Published',
        eu_platform: 'Yes',
        type_pid_repo: 'DOI',
        pid: null,
        pid_pub: 'doi.org/10.1007/978-3-031-37709-9_1',
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'A flexible toolchain for symbolic rabin games under fair and stochastic uncertainties',
        authors:
            'Rupak Majumdar, Kaushik Mallik, Mateusz Rychlicki, Anne-Kathrin Schmuck & Sadegh Soudjani',
        journal: 'International Conference on Computer Aided Verification 2023',
        number: null,
        issn: '',
        publisher: 'Springer, Cham',
        month: 'July',
        year: '2023',
        open_access: true,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'MPI',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1007/978-3-031-37709-9_1',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1145/360810',
        pid_pub: 'https://arxiv.org/abs/2307.03783',
        type_pub: 'Article in Journal',
        link: 'https://dl.acm.org/doi/full/10.1145/3608104',
        title: 'Neural Abstraction-Based Controller Synthesis and Deployment',
        authors: 'Rupak Majumdar, Mahmoud Salamati, Sadegh Soudjani',
        journal: 'ACM Transactions on Embedded Computing Systems',
        number: 'Vol. 22, No. 5s',
        issn: '',
        publisher: 'ACM',
        month: 'September',
        year: '2023',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1145/3608104',
    },
    {
        date: '2023-09-19T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: null,
        pid_pub: '10.48550/arXiv.2306.03220',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2306.03220',
        title: 'Risk-Aware Reward Shaping of Reinforcement Learning Agents for Autonomous Driving',
        authors:
            'Lin-Chi Wu, Zengjie Zhang, Sofie Haesaert, Zhiqiang Ma, Zhiyong Sun',
        journal: 'IECON 2023',
        number: null,
        issn: '',
        publisher: 'IECON',
        month: 'October',
        year: '2023',
        open_access: true,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'TU/e',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/iecon51785.2023.10312462',
    },
    {
        date: '2023-09-28T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1109/SMC53992.2023.10394593',
        pid_pub: 'https://doi.org/10.48550/arXiv.2310.16760',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2310.16760#',
        title: 'Using Knowledge Awareness to improve Safety of Autonomous Driving',
        authors: 'Andrea Calvagna, Arabinda Ghosh, Sadegh Soudjani',
        journal: '2023 IEEE Conference on Systems, Man, and Cybernetics',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'October',
        year: '2023',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'NO',
        apc_charged: null,
        consortium_partner: 'MPI',
        topic: 'Knowledge AwarenesKnowledge AwarenesxKnowledge Awareness',
        data_used: 'Synthetic data for simulations',
        data_zenodo: 'Yes (https://zenodo.org/records/10041525)',
        doi: '10.1109/smc53992.2023.10394593',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1109/OJCSYS.2023.3329394',
        pid_pub: 'https://arxiv.org/abs/2208.03485',
        type_pub: 'Article in Journal',
        link: 'https://ieeexplore.ieee.org/abstract/document/10304199',
        title: 'Compositional reinforcement learning for discrete-time stochastic control systems',
        authors:
            'Abolfazl Lavaei, Mateo Perez, Milad Kazemi, Fabio Somenzi, Sadegh Soudjani, Ashutosh Trivedi, Majid Zamani',
        journal: ' IEEE Open Journal of Control Systems ',
        number: 'Volume 2, pp. 425-438, 2023',
        issn: '2694-085X',
        publisher: 'IEEE',
        month: 'November',
        year: '2023',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1109/OJCSYS.2023.3329394',
    },
    {
        date: '2023-09-19T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: null,
        pid_pub: '10.48550/arXiv.2304.00275',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2304.00275',
        title: 'Automated Formation Control Synthesis from Temporal Logic Specifications',
        authors: 'Shuhao Qi, Zengjie Zhang, Sofie Haesaert, Zhiyong Sun',
        journal: ' 62nd IEEE Conference on Decision and Control (CDC 2023) ',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'December',
        year: '2023',
        open_access: true,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'TU/e',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc49753.2023.10383729',
    },
    {
        date: '2023-09-19T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: null,
        pid_pub: '10.48550/arXiv.2303.17086',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2303.17086',
        title: 'Modularized Control Synthesis for Complex Signal Temporal Logic Specifications',
        authors: 'Zengjie Zhang, Sofie Haesaert',
        journal: ' 62nd IEEE Conference on Decision and Control (CDC 2023) ',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'December',
        year: '2023',
        open_access: true,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'TU/e',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc49753.2023.10383263',
    },
    {
        date: '2019-09-23T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: ' Corridor MPC for Multi-Agents Inspection of Orbiting Structures',
        authors: 'Gregorio Marchesini, Pedro Roque, Dimos Dimarogonas',
        journal: ' 62nd IEEE Conference on Decision and Control (CDC 2023) ',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'December',
        year: '2023',
        open_access: true,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc49753.2023.10383291',
    },
    {
        date: '2019-09-23T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2305.05294',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2305.05294',
        title: 'Construction of Control Barrier Functions Using Predictions with Finite Horizon',
        authors: 'Adrian Wiltz, Xiao Tan, Dimos V. Dimarogonas',
        journal: ' 62nd IEEE Conference on Decision and Control (CDC 2023) ',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'December',
        year: '2023',
        open_access: true,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc49753.2023.10383564',
    },
    {
        date: '2020-09-23T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: null,
        pid_pub: '10.48550/arXiv.2309.07347',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://aps.arxiv.org/abs/2309.07347',
        title: 'Energy-Constrained Active Exploration Under Incremental-Resolution Symbolic Perception',
        authors: 'Disha Kamale, Sofie Haesaert, Cristian-Ioan Vasile',
        journal: ' 62nd IEEE Conference on Decision and Control (CDC 2023) ',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'December',
        year: '2023',
        open_access: null,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'TU/e',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc49753.2023.10383606',
    },
    {
        date: '2024-09-12T00:00:00.000',
        status: 'Accepted',
        eu_platform: null,
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Risk-aware reward shaping of reinforcement learning agents for autonomous driving',
        authors:
            'Wu, Lin-Chi, Zengjie Zhang, Sofie Haesaert, Zhiqiang Ma, and Zhiyong Sun',
        journal:
            'IECON 2023-49th Annual Conference of the IEEE Industrial Electronics Society',
        number: 'pp. 1-6',
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2023',
        open_access: null,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: null,
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/iecon51785.2023.10312462',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1016/j.automatica.2023.111323',
        pid_pub: 'https://arxiv.org/abs/2111.10330',
        type_pub: 'Article in Journal',
        link: 'https://www.sciencedirect.com/science/article/pii/S0005109823004892',
        title: 'Data-driven verification and synthesis of stochastic systems via barrier certificates',
        authors: 'Ali Salamati, Abolfazl Lavaei, Sadegh Soudjani, Majid Zamani',
        journal: 'Automatica',
        number: 'Volume 159, January 2024, 111323',
        issn: '1873-2836',
        publisher: 'Elsevier',
        month: 'January',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1016/j.automatica.2023.111323',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1109/CDC49753.2023.10384033',
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://ieeexplore.ieee.org/abstract/document/10384033',
        title: 'Temporal Logic Resilience for Cyber-Physical Systems',
        authors: 'Adnane Saoud; Pushpak Jagtap; Sadegh Soudjani',
        journal: '2023 62nd IEEE Conference on Decision and Control (CDC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'January',
        year: '2024',
        open_access: false,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1109/CDC49753.2023.10384033',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1016/j.nahs.2023.101430',
        pid_pub: 'https://arxiv.org/abs/2101.00834',
        type_pub: 'Article in Journal',
        link: 'https://www.sciencedirect.com/science/article/pii/S1751570X23001012',
        title: 'Symbolic control for stochastic systems via finite parity games',
        authors:
            'Rupak Majumdar, Kaushik Mallik, Anne-Kathrin Schmuck, Sadegh Soudjani',
        journal: 'Nonlinear Analysis: Hybrid Systems',
        number: 'Volume 51, 101430',
        issn: '1878-7460',
        publisher: 'Elsevier',
        month: 'February',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1016/j.ifacol.2021.08.486',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: 'https://arxiv.org/abs/2403.05350',
        pid_pub: 'https://arxiv.org/abs/2403.05350',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://proceedings.mlr.press/v238/zhang24i.html',
        title: 'Formal verification of unknown stochastic systems via non-parametric estimation',
        authors: 'Zhi Zhang, Chenyu Ma, Saleh Soudijani, Sadegh Soudjani ',
        journal:
            'Proceedings of The 27th International Conference on Artificial Intelligence and Statistics, PMLR',
        number: 'Volume 238',
        issn: '',
        publisher: 'PMLR',
        month: 'March',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2403.05350',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1609/aaai.v38i19.30116',
        pid_pub: 'https://arxiv.org/abs/2312.09938',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://ojs.aaai.org/index.php/AAAI/article/view/30116',
        title: 'Assume-Guarantee Reinforcement Learning',
        authors:
            'Milad Kazemi, Mateo Perez, Fabio Somenzi, Sadegh Soudjani, Ashutosh Trivedi, Alvaro Velasquez',
        journal:
            'Proceedings of the AAAI Conference on Artificial Intelligence',
        number: 'Volume 38 Issue 19 Pages 21223-21231',
        issn: '',
        publisher: 'AAAI',
        month: 'March',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1609/aaai.v38i19.30116',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2404.19223',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2404.19223',
        title: 'Temporal logic resilience for dynamical systems',
        authors: 'Adnane Saoud, Pushpak Jagtap, Sadegh Soudjani',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: null,
        month: 'April',
        year: '2024',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2404.19223',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1016/j.nahs.2024.101467',
        pid_pub: 'https://arxiv.org/abs/2206.08069',
        type_pub: 'Article in Journal',
        link: 'https://www.sciencedirect.com/science/article/pii/S1751570X24000049',
        title: 'Data-Driven Abstraction-Based Control Synthesis',
        authors:
            'Milad Kazemi, Rupak Majumdar, Mahmoud Salamati, Sadegh Soudjani, Ben Wooding',
        journal: 'Nonlinear Analysis: Hybrid Systems',
        number: 'Volume 52, May 2024, 101467',
        issn: '1878-7460',
        publisher: 'Elsevier',
        month: 'May',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1016/j.nahs.2024.101467',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2407.03896',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2407.03896',
        title: 'Specification-guided temporal logic control for stochastic systems: a multi-layered approach',
        authors:
            'Birgit C van Huijgevoort, Ruohan Wang, Sadegh Soudjani, Sofie Haesaert',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: null,
        month: 'July',
        year: '2024',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, TU/e',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1145/2461328.2461378',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.23919/ECC64448.2024.10591078',
        pid_pub:
            'https://www.researchgate.net/profile/Arash-Bahari-Kordabad/publication/382543432_Control_Barrier_Functions_for_Stochastic_Systems_under_Signal_Temporal_Logic_Tasks/links/66a3819dde060e4c7e5c3afa/Control-Barrier-Functions-for-Stochastic-Systems-under-Signal-Temporal-Logic-Tasks.pdf',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://ieeexplore.ieee.org/abstract/document/10591078',
        title: 'Control Barrier Functions for Stochastic Systems under Signal Temporal Logic Tasks',
        authors:
            'Arash Bahari Kordabad, Maria Charitidou, Dimos V Dimarogonas, Sadegh Soudjani',
        journal: '2024 European Control Conference (ECC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'July',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, KTH',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.23919/ecc64448.2024.10591078',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2409.14833',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2409.14833',
        title: 'SymAware: A Software Development Framework for Trustworthy Multi-Agent Systems with Situational Awareness',
        authors:
            'Ernesto Casablanca, Zengjie Zhang, Gregorio Marchesini, Sofie Haesaert, Dimos V. Dimarogonas, Sadegh Soudjani',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: null,
        month: 'September',
        year: '2024',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, TU/e, KTH',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2409.14833',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1109/TAC.2024.3459308',
        pid_pub: 'https://arxiv.org/abs/2304.07428',
        type_pub: 'Article in Journal',
        link: 'https://ieeexplore.ieee.org/abstract/document/10678810',
        title: 'Bayesian formal synthesis of unknown systems via robust simulation relations',
        authors:
            'liver Sch\u00f6n, Birgit van Huijgevoort, Sofie Haesaert, Sadegh Soudjani',
        journal: 'IEEE Transactions on Automatic Control',
        number: 'Volume: 70, Issue: 3, March 2025',
        issn: '1558-2523',
        publisher: 'IEEE',
        month: 'September',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, TU/e',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1109/tac.2024.3459308',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.23919/ACC60939.2024.10644349',
        pid_pub: 'https://arxiv.org/abs/2403.10497',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://ieeexplore.ieee.org/abstract/document/10644349',
        title: 'Data-Driven Distributionally Robust Safety Verification Using Barrier Certificates and Conditional Mean Embeddings',
        authors: 'Oliver Sch\u00f6n, Zhengang Zhong, Sadegh Soudjani',
        journal: '2024 American Control Conference (ACC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'September',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.23919/acc60939.2024.10644349',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2411.08754',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2411.08754',
        title: 'Logic-based Knowledge Awareness for Autonomous Agents in Continuous Spaces',
        authors: 'Arabinda Ghosh, Mahmoud Salamati, Sadegh Soudjani',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: null,
        month: 'November',
        year: '2024',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2411.08754',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1109/CDC56724.2024.10886437',
        pid_pub: 'https://arxiv.org/pdf/2409.03855',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://ieeexplore.ieee.org/abstract/document/10886437',
        title: 'Distributionally Robust Control for Chance-Constrained Signal Temporal Logic Specifications',
        authors:
            'Arash Bahari Kordabad, Eleftherios E Vlahakis, Lars Lindemann, Dimos V Dimarogonas, Sadegh Soudjani',
        journal: '2024 IEEE 63rd Conference on Decision and Control (CDC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'December',
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, KTH',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1109/cdc56724.2024.10886437',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Decentralized Control of Multi-Agent Systems under Acyclic Spatio-Temporal Task Dependencies',
        authors:
            'Gregorio Marchesini, Siyuan Liu, Lars Lindemann and Dimos V. Dimarogonas',
        journal: 'CDC 2024',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2024',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc56724.2024.10885877',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Communication-Constrained STL Task Decomposition through Convex Optimization',
        authors:
            'Gregorio Marchesini, Siyuan Liu, Lars Lindemann and Dimos V. Dimarogonas',
        journal: 'ACC 2024',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2024',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.23919/acc60939.2024.10644859',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Distributed Sequential Receding Horizon Control of Multi-Agent Systems Under Recurring Signal Temporal Logic',
        authors: 'E. E. Vlahakis, L. Lindemann and D. V. Dimarogonas',
        journal: 'ECC2024',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2024',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.23919/ecc64448.2024.10590994',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: null,
        title: 'Conformal Prediction for Distribution-Free Optimal Control of Linear Stochastic Systems',
        authors:
            'E. E. Vlahakis, L. Lindemann, P. Sopasakis and D. V. Dimarogonas',
        journal: 'IEEE Control Systems Letters',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2024',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.48550/arXiv.2504.04615',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Probabilistic Tube-based Control Synthesis of Stochastic Multi-Agent Systems under Signal Temporal Logic',
        authors:
            'E. E. Vlahakis, L. Lindemann, P. Sopasakis and D. V. Dimarogonas',
        journal: 'CDC2024',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2024',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc56724.2024.10886279',
    },
    {
        date: '2017-09-25T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Formalizing Vocabulary for Scenario-Based Testing of Automated Driving Systems: From Semantics to Mathematics',
        authors:
            'KT Kurian, N Rajesh, E Lefeber, J Ploeg, N Van De Wouw, I Besselink, M. Alirezaei',
        journal: '27th International Conference on Intelligent Transportation',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2024',
        open_access: null,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: null,
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/itsc58415.2024.10919488',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1109/LCSYS.2024.3507279',
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: 'https://ieeexplore.ieee.org/abstract/document/10769425',
        title: 'Necessary and Sufficient Certificates for Almost Sure Reachability',
        authors: 'Rupak Majumdar; V. R. Sathiyanarayana; Sadegh Soudjani',
        journal: 'IEEE Control Systems Letters',
        number: 'Volume: 8',
        issn: ' 2475-1456',
        publisher: 'IEEE',
        month: 'Novemver',
        year: '2024',
        open_access: false,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1109/lcsys.2024.3507279',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1016/j.ifacol.2024.07.432',
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: 'https://www.sciencedirect.com/science/article/pii/S2405896324005317',
        title: 'Lyapunov-Based Policy Synthesis for Multi-Objective Interval MDP',
        authors: 'Negar Monir, Oliver Sch\u00f6n, Sadegh Soudjani',
        journal: 'IFAC-PapersOnLine',
        number: 'Volume 58, Issue 11, 2024, Pages 99-106',
        issn: '2405-8963',
        publisher: 'Elsevier',
        month: null,
        year: '2024',
        open_access: false,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1016/j.ifacol.2024.07.432',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1016/j.ifacol.2024.07.434',
        pid_pub: 'https://arxiv.org/abs/2407.21029',
        type_pub: 'Article in Journal',
        link: 'https://www.sciencedirect.com/science/article/pii/S2405896324005330',
        title: 'Data-driven abstractions via binary-tree Gaussian processes for formal verification',
        authors:
            'Oliver Sch\u00f6n, Shammakh Naseer, Ben Wooding, Sadegh Soudjani',
        journal: 'IFAC-PapersOnLine',
        number: 'Volume 58, Issue 11, 2024, Pages 115-122',
        issn: '2405-8964',
        publisher: 'Elsevier',
        month: null,
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1016/j.ifacol.2024.07.434',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1016/j.ifacol.2024.07.433',
        pid_pub: 'https://arxiv.org/pdf/2404.18813',
        type_pub: 'Article in Journal',
        link: 'https://www.sciencedirect.com/science/article/pii/S2405896324005329',
        title: 'Safe reach set computation via neural barrier certificates',
        authors:
            'Alessandro Abate, Sergiy Bogomolov, Alec Edwards, Kostiantyn Potomkin, Sadegh Soudjani, Paolo Zuliani',
        journal: 'IFAC-PapersOnLine',
        number: 'Volume 58, Issue 11, 2024, Pages 107-114',
        issn: '2405-8965',
        publisher: 'Elsevier',
        month: null,
        year: '2024',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1016/j.ifacol.2024.07.433',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1007/978-3-031-76424-0_20',
        pid_pub: 'https://arxiv.org/pdf/2402.09030',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://link.springer.com/chapter/10.1007/978-3-031-76424-0_20ttps://arxiv.org/pdf/2402.09030',
        title: 'Awareness in Robotics: An Early Perspective from the Viewpoint of the EIC Pathfinder Challenge \u201cAwareness Inside\u201d',
        authors:
            'Cosimo Della Santina, Carlos Hernandez Corbato, Burak Sisman, Luis A. Leiva, Ioannis Arapakis, Michalis Vakalellis, Jean Vanderdonckt, Luis Fernando D\u2019Haro, Guido Manzi, Cristina Becchio, A\u00efda Elamrani, Mohsen Alirezaei, Ginevra Castellano, Dimos V. Dimarogonas, Arabinda Ghosh, Sofie Haesaert, Sadegh Soudjani, Sybert Stroeve, Paul Verschure, Davide Bacciu, Ophelia Deroy, Bahador Bahrami, Claudio Gallicchio, Sabine Hauert, Ricardo Sanz, Pablo Lanillos, Giovanni Iacca, Stephan Sigg, Manel Gasulla, Luc Steels & Carles Sierra ',
        journal: 'European Robotics Forum 2024 ',
        number: 'Volume 32  ',
        issn: '978-3-031-76424-0',
        publisher: 'Springer',
        month: 'January',
        year: '2025',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: 'Springer Proceedings in Advanced Robotics',
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'all partners',
        topic: null,
        data_used: '-',
        data_zenodo: '-',
        doi: '10.1007/978-3-031-76424-0_20',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: ' 10.1109/CDC49753.2023.10383307',
        pid_pub: 'https://arxiv.org/abs/2309.01276',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://ieeexplore.ieee.org/abstract/document/10383307',
        title: 'Verifying the Unknown: Correct-by-Design Control Synthesis for Networks of Stochastic Uncertain Systems',
        authors:
            'Oliver Sch\u00f6n, Birgit van Huijgevoort, Sofie Haesaert, Sadegh Soudjani',
        journal: '2023 62nd IEEE Conference on Decision and Control (CDC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'February',
        year: '2025',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI_SWS, TU/e',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1109/cdc49753.2023.10383307',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2503.23518 ',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2503.23518',
        title: 'Intent-Aware MPC for Aircraft Detect-and-Avoid with Response Delay: A Comparative Study with ACAS Xu',
        authors:
            'Arash Bahari Kordabad, Arabinda Ghosh, Sybert Stroeve, Sadegh Soudjani',
        journal: 'Arxiv',
        number: null,
        issn: '',
        publisher: 'arxiv',
        month: 'March',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'NO',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, NLR',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2503.23518',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2503.09816 ',
        type_pub: 'Article in Journal',
        link: 'https://arxiv.org/abs/2503.09816',
        title: 'Data-Driven Distributionally Robust Control for Interacting Agents under Logical Constraints',
        authors:
            'Arash Bahari Kordabad, Eleftherios E Vlahakis, Lars Lindemann, Sebastien Gros, Dimos V Dimarogonas, Sadegh Soudjani',
        journal: 'Arxiv',
        number: null,
        issn: '',
        publisher: 'Arxiv',
        month: 'March',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, KTH',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2503.09816',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1109/ITSC58415.2024.10920039',
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://ieeexplore.ieee.org/abstract/document/10920039',
        title: 'Rare collision risk estimation of autonomous vehicles with multi-agent situation awareness',
        authors:
            'Mahdieh Zaker, Henk AP Blom, Sadegh Soudjani, Abolfazl Lavaei',
        journal:
            '2024 IEEE 27th International Conference on Intelligent Transportation Systems (ITSC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: 'March',
        year: '2025',
        open_access: false,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1109/itsc58415.2024.10920039',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2408.06999',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2408.06999',
        title: 'Robust model predictive control for aircraft intent-aware collision avoidance',
        authors:
            'Arash Bahari Kordabad, Andrea Da Col, Arabinda Ghosh, Sybert Stroeve, Sadegh Soudjani',
        journal: 'European Control Conferences 2025',
        number: null,
        issn: '',
        publisher: null,
        month: 'March',
        year: '2025',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, NLR',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.23919/ecc65951.2025.11186903',
    },
    {
        date: '2025-05-30T00:00:00.000',
        status: 'Accepted',
        eu_platform: null,
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1007/978-3-031-78357-9_4',
        pid_pub: null,
        type_pub: 'Chapter in Journal',
        link: 'https://link.springer.com/chapter/10.1007/978-3-031-78357-9_4',
        title: 'Examining Human\u2013Robot Interactions: Design Guidelines for Trust and Acceptance',
        authors:
            'Natalia Calvo Barajas, Alexandros Rouchitsas & Didem G\u00fcrd\u00fcr Broo ',
        journal:
            'Malakhatka, E., Wiberg, M. (eds) Human-Technology Interaction. Springer Series in Adaptive Environments',
        number: null,
        issn: '978-3-031-78357-9',
        publisher: 'Springer, Cham',
        month: 'April',
        year: '2025',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'Uppsala University',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1007/978-3-031-78357-9_4',
    },
    {
        date: '2025-09-19T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.1145/3706599.3719695',
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://dl.acm.org/doi/abs/10.1145/3706599.3719695 ',
        title: 'Visualizing Confidence in Delivery Robots: Insights from Two Online Studies',
        authors:
            'Ronald Cumbal, Natalia Calvo-Barajas, Marina Escobar-Planas, Alexandros Rouchitsas, Ginevra Castellano',
        journal:
            'Proceedings of the Extended Abstracts of the CHI Conference on Human Factors in Computing Systems',
        number: 578,
        issn: '9798400713958',
        publisher: 'Association for Computing Machinery',
        month: 'April',
        year: '2025',
        open_access: false,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: true,
        consortium_partner: 'Uppsala University',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1145/3706599.3719695',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2505.15693',
        type_pub: 'Article in Journal',
        link: 'https://arxiv.org/abs/2505.15693',
        title: 'Average Reward Reinforcement Learning for Omega-Regular and Mean-Payoff Objectives',
        authors:
            'Milad Kazemi, Mateo Perez, Fabio Somenzi, Sadegh Soudjani, Ashutosh Trivedi, Alvaro Velasquez ',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: 'arxiv',
        month: 'May',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2505.15693',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2505.06943',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2505.06943',
        title: 'Robust Control of Uncertain Switched Affine Systems via Scenario Optimization',
        authors: 'Negar Monir, Mahdieh S. Sadabadi, Sadegh Soudjani',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: 'arxiv',
        month: 'May',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, Newcastle',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2505.06943',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2506.16971',
        type_pub: 'Article in Journal',
        link: 'https://arxiv.org/abs/2506.16971',
        title: 'Formal Control for Uncertain Systems via Contract-Based Probabilistic Surrogates (Extended Version)',
        authors: 'Oliver Sch\u00f6n, Sofie Haesaert, Sadegh Soudjani',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: 'arxiv',
        month: 'June',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, TU/e',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1007/978-3-032-05792-1_4',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2411.12019',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2411.12019',
        title: 'Regret-Free Reinforcement Learning for LTL Specifications',
        authors: 'Rupak Majumdar, Mahmoud Salamati, Sadegh Soudjani',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: null,
        month: 'June',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2411.12019',
    },
    {
        date: '2025-09-23T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'Researchgate link',
        pid: 'https://www.researchgate.net/profile/Sybert-Stroeve/publication/393018201_Including_intent_in_detect-and-avoid_systems_for_remotely_piloted_aircraft_systems/links/685c4eeecdf1a35eb1754119/Including-intent-in-detect-and-avoid-systems-for-remotely-piloted-aircraft-systems.pdf',
        pid_pub:
            'https://www.researchgate.net/profile/Sybert-Stroeve/publication/393018201_Including_intent_in_detect-and-avoid_systems_for_remotely_piloted_aircraft_systems/links/685c4eeecdf1a35eb1754119/Including-intent-in-detect-and-avoid-systems-for-remotely-piloted-aircraft-systems.pdf',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://www.researchgate.net/profile/Sybert-Stroeve/publication/393018201_Including_intent_in_detect-and-avoid_systems_for_remotely_piloted_aircraft_systems/links/685c4eeecdf1a35eb1754119/Including-intent-in-detect-and-avoid-systems-for-remotely-piloted-aircraft-systems.pdf',
        title: 'Including intent in detect-and-avoid systems for remotely piloted aircraft systems',
        authors: 'Sybert Stroeve, Mirco Kroon ',
        journal:
            'Air Transportation Research and Development Symposium (ATRDS2025)',
        number: null,
        issn: '',
        publisher: null,
        month: 'June',
        year: '2025',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'NLR',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '',
    },
    {
        date: '2025-09-19T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.3389/frobt.2025.1547578',
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: null,
        title: 'UpStory: the uppsala storytelling dataset',
        authors:
            'Marc Fraile, Natalia Calvo-Barajas, Anastasia Sophia Apeiron, Giovanna Varni, Joakim Lindblad, Nata\u0161a Sladoje, Ginevra Castellano',
        journal: 'Frontiers in Robotics and AI',
        number: 12,
        issn: '2296-9144',
        publisher: 'Frontiers',
        month: 'July',
        year: '2025',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'no',
        apc_charged: false,
        consortium_partner: 'Uppsala University',
        topic: null,
        data_used: null,
        data_zenodo: 'yes, https://zenodo.org/records/15391848 ',
        doi: '10.3389/frobt.2025.1547578',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2507.20194',
        type_pub: 'Article in Journal',
        link: 'https://arxiv.org/abs/2507.20194',
        title: 'On Certificates for Almost Sure Reachability in Stochastic Systems',
        authors:
            'Arash Bahari Kordabad, Rupak Majumdar, Harshit Jitendra Motwani, Sadegh Soudjani ',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: 'arxiv',
        month: 'July',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2507.20194',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2508.15543',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2508.15543',
        title: 'Data-Driven Abstraction and Synthesis for Stochastic Systems with Unknown Dynamics',
        authors:
            'Mahdi Nazeri, Thom Badings, Anne-Kathrin Schmuck, Sadegh Soudjani, Alessandro Abate',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: 'arxiv',
        month: 'August',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.23919/acc45564.2020.9147725',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2501.01191',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2501.01191',
        title: 'Data-driven yet formal policy synthesis for stochastic nonlinear dynamical systems',
        authors:
            'Mahdi Nazeri, Thom Badings, Sadegh Soudjani, Alessandro Abate',
        journal: 'Arxiv',
        number: null,
        issn: '',
        publisher: 'Arxiv',
        month: 'August',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2501.01191',
    },
    {
        date: '2025-09-19T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: '10.3389/frobt.2025.1657857',
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: 'https://www.frontiersin.org/journals/robotics-and-ai/articles/10.3389/frobt.2025.1657857/full',
        title: 'Information vs. Situation: Balancing Transparency and Autonomy for Trustworthy Autonomous Vehicles',
        authors: 'Ana Tanevska, Katie Winkle, Ginevra Castellano',
        journal: 'Frontiers in Robotics and AI',
        number: 'Volume 12 - 2025',
        issn: '',
        publisher: 'Frontiers',
        month: 'September',
        year: '2025',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'Uppsala University',
        topic: null,
        data_used: 'User study',
        data_zenodo: 'https://zenodo.org/records/15648216',
        doi: '10.3389/frobt.2025.1657857',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'arXiv:2509.01777',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2509.01777',
        title: 'Maximally Resilient Controllers under Temporal Logic Specifications',
        authors:
            'Youssef Ait Si, Ratnangshu Das, Negar Monir, Sadegh Soudjani, Pushpak Jagtap, Adnane Saoud',
        journal: 'Arxiv',
        number: null,
        issn: '',
        publisher: 'Arxiv',
        month: 'September',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, Newcastle',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2509.01777',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'In review',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: ' arXiv:2509.01832',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2509.01832',
        title: 'Computation of Feasible Assume-Guarantee Contracts: A Resilience-based Approach ',
        authors:
            'Negar Monir, Youssef Ait Si, Ratnangshu Das, Pushpak Jagtap, Adnane Saoud, Sadegh Soudjani',
        journal: 'Arxiv',
        number: null,
        issn: '',
        publisher: 'Arxiv',
        month: 'September',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, Newcastle',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2509.01832',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'In review',
        eu_platform: 'No',
        type_pid_repo: 'arxiv link',
        pid: null,
        pid_pub: 'https://arxiv.org/abs/2509.01832',
        type_pub: 'Publication in conference proceeding/workshop',
        link: 'https://arxiv.org/abs/2509.01832',
        title: 'Computation of Feasible Assume-Guarantee Contracts: A Resilience-based Approach',
        authors:
            'Negar Monir, Youssef Ait Si, Ratnangshu Das, Pushpak Jagtap, Adnane Saoud, Sadegh Soudjani',
        journal: 'arxiv',
        number: null,
        issn: '',
        publisher: null,
        month: 'September',
        year: '2025',
        open_access: true,
        peer_reviewed: false,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS',
        topic: null,
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.48550/arXiv.2509.01832',
    },
    {
        date: '2025-09-22T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.1016/j.nahs.2025.101607',
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: 'https://www.sciencedirect.com/science/article/abs/pii/S1751570X25000330',
        title: 'SySCoRe 2.0: Toolset for formal control synthesis of continuous-state stochastic systems and temporal logic specifications',
        authors:
            'B.C. van Huijgevoort , M.H.W. Engelaar , S. Soudjani , S. Haesaert',
        journal: 'Nonlinear Analysis: Hybrid Systems',
        number: 'Volume 58, November 2025, 101607',
        issn: '1878-7460',
        publisher: 'Elsevier\u00a0',
        month: 'November',
        year: '2025',
        open_access: false,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'No',
        apc_charged: null,
        consortium_partner: 'MPI-SWS, TU/e',
        topic: 'controllers for stochastic systems to satisfy temporal logic specifications',
        data_used: 'Synthetic data for simulation',
        data_zenodo: 'No',
        doi: '10.1016/j.nahs.2025.101607',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'In review',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: 'arXiv:2410.12563',
        title: 'A Communication Consistent Approach to Signal Temporal Logic Task Decomposition in Multi-Agent Systems',
        authors:
            'Gregorio Marchesini, Siyuan Liu, Lars Lindemann and Dimos V. Dimarogonas',
        journal: 'IEEE Transactions on Automatic Control (TAC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.23919/acc.2017.7963331',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: null,
        title: 'Controller Synthesis of Collaborative Signal Temporal Logic Tasks for Multi-Agent Systems via Assume-Guarantee Contracts',
        authors: 'Siyuan Liu, Adnane Saoud and Dimos V. Dimarogonas',
        journal: 'IEEE Transactions on Automatic Control (TAC)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/cdc51059.2022.9992715',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Transient Control of Linear Multi-Agent Systems with Leader-Follower Configuration',
        authors: 'Siyuan Liu, Fei Chen and Dimos V. Dimarogonas',
        journal: 'ACC 2025',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.23919/acc63710.2025.11107638',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'Communication-aware Multi-agent Systems Control Based on k-hop Distributed Observers',
        authors: 'Tommaso Zaccherini, Siyuan Liu and Dimos V. Dimarogonas',
        journal: 'ECC2025',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.23919/ecc65951.2025.11187218',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'Accepted',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: null,
        title: 'Multi-Agent Estimation and Control Based on a Novel k-hop Distributed Prescribed Performance Observer',
        authors: 'Tommaso Zaccherini, Siyuan Liu and Dimos V. Dimarogonas',
        journal: 'IEEE Control Systems Letters',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/lcsys.2025.3575247',
    },
    {
        date: '2025-06-09T00:00:00.000',
        status: 'In review',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Article in Journal',
        link: 'https://arxiv.org/abs/2504.04615',
        title: 'Conformal data-driven control of stochastic multi-agent systems under collaborative signal temporal logic specifications',
        authors: 'E. E. Vlahakis, L. Lindemann, and D. V. Dimarogonas',
        journal: 'arXiv',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: null,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: 'KTH',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.23919/ecc55457.2022.9838497',
    },
    {
        date: '2017-09-25T00:00:00.000',
        status: 'Published',
        eu_platform: 'No',
        type_pid_repo: null,
        pid: null,
        pid_pub: null,
        type_pub: 'Publication in conference proceeding/workshop',
        link: null,
        title: 'How unsafe was the scenario? A criticality measure for scenario-based testing of automated vehicles',
        authors:
            'KT Kurian, N Rajesh, E Lefeber, J Ploeg, N van de Wouw, I Besselink, M Alirezaei',
        journal: 'IEEE Intelligent Vehicles Symposium',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: null,
        peer_reviewed: null,
        pid_book: null,
        book_title: null,
        oa_fees: null,
        apc_charged: null,
        consortium_partner: null,
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.1109/iv64158.2025.11097344',
    },
    {
        date: '2025-09-19T00:00:00.000',
        status: 'Accepted/Presented',
        eu_platform: 'No',
        type_pid_repo: 'DOI',
        pid: 'https://doi.org/10.48550/arXiv.2506.21322',
        pid_pub: null,
        type_pub: null,
        link: 'https://arxiv.org/abs/2506.21322',
        title: '\u201cWho Should I Believe?\u201d: User Interpretation and Decision-Making When a Family Healthcare Robot Contradicts Human Memory',
        authors:
            'Hong Wang, Natalia Calvo-Barajas, Katie Winkle, Ginevra Castellano',
        journal:
            '2025 34th IEEE International Conference on Robot and Human Interactive Communication (RO-MAN)',
        number: null,
        issn: '',
        publisher: 'IEEE',
        month: null,
        year: '2025',
        open_access: true,
        peer_reviewed: true,
        pid_book: null,
        book_title: null,
        oa_fees: 'no',
        apc_charged: false,
        consortium_partner: 'Uppsala University',
        topic: null,
        data_used: null,
        data_zenodo: null,
        doi: '10.48550/arXiv.2506.21322',
    },
]
