export const members = [
  // {
  //     image: "",
  //     name: "",
  //     description: "",
  // },
  // {
  //     name: "Ben Wooding",
  //     image: "../../assets/images/people/Ben_Wooding.png",
  //     description: "Phd Student",
  //     institution: "mpi",
  //     role: "phd",
  //     partner: "academic",
  // },
  // {
  //     name: "Ana Laino",
  //     image: "../../assets/images/people/Ana_Laino.png",
  //     description: "Phd Student",
  //     institution: "mpi",
  //     role: "phd",
  //     partner: "academic",
  // },
  {
    name: "Patrick Jonk",
    image: "../../assets/images/people/patrick-jonk.jfif",
    description: "R&D Engineer",
    institution: "nlr",
    role: "phd",
    partner: "industry",
  },
  {
    name: "Ana Tanevska",
    image: "../../assets/images/people/ana-tanevska.png",
    description: "Postdoctoral Researcher",
    institution: "uu",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Didem Gürdür Broo",
    image: "../../assets/images/people/didem-gurdur-broo.png",
    description: "Assistant Professor",
    institution: "uu",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Lefteris Vlahakis",
    image: "../../assets/images/people/lefteris-vlahakis.jpg",
    description: "Postdoctoral Researcher",
    institution: "kth",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Siyuan Liu",
    image: "../../assets/images/people/siyuan-liu.jpg",
    description: "Postdoctoral Researcher",
    institution: "kth",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Gregorio Marchesini",
    image: "../../assets/images/people/gregorio-marchesini.png",
    description: "PhD Student",
    institution: "kth",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Birgit Van Huijgevoort",
    image: "../../assets/images/people/birgit-van-huijgevoort.jpg",
    description: "Doctoral Candidate",
    institution: "tu/e",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Zengjie Zhang",
    image: "../../assets/images/people/zengjie-zhang.jpg",
    description: "Assistant Professor",
    institution: "tu/e",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Ruohan Wang",
    image: "../../assets/images/people/ruohan-wang.jpg",
    description: "PhD Student",
    institution: "tu/e",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Erjen Lefeber",
    image: "../../assets/images/people/erjen-lefeber.jpg",
    description: "Assistant Professor",
    institution: "tu/e",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Kevin Tom  Kurian",
    image: "../../assets/images/people/kevin-tom-kurian.jpg",
    description: "Doctoral Candidate",
    institution: "tu/e",
    role: "phd",
    partner: "academic",
  },
  {
    name: "Igo Besselink",
    image: "../../assets/images/people/igo-besselink.jpg",
    description: "Assistant Professor",
    institution: "tu/e",
    role: "phd",
    partner: "academic",
  },
];

export const leaders = [
  // {
  //     name: "",
  //     image: "",
  //     companyLogo: "",
  // },
  {
    id: 1,
    name: "Sadegh Soudjani",
    image: "../../assets/images/people/sadegh-soudjani.png",
    companyLogo: "../../assets/images/consortium/mpi.png",
    institution: "mpi",
    role: "Project Coordinator",
    partner: "academic",
  },
  {
    id: 2,
    name: "Sofie Haesaert",
    image: "../../assets/images/people/sofie-haesaert.png",
    companyLogo: "../../assets/images/consortium/tue.png",
    institution: "tu/e",
    role: "Partner",
    partner: "academic",
  },
  {
    id: 3,
    name: "Dimos Dimorogonas",
    image: "../../assets/images/people/dimos-dimorogonas.png",
    companyLogo: "../../assets/images/consortium/kth.png",
    institution: "kth",
    role: "Partner",
    partner: "academic",
  },
  {
    id: 4,
    name: "Ginevra Castellano",
    image: "../../assets/images/people/ginevra-castellano.png",
    companyLogo: "../../assets/images/consortium/uu.png",
    institution: "uu",
    role: "Principal Investigator",
    partner: "academic",
  },
  {
    id: 5,
    name: "Mohsen Allrezael",
    image: "../../assets/images/people/mohsen-allrezael.png",
    companyLogo: "../../assets/images/consortium/siemens.png",
    institution: "siemens",
    role: "Partner",
    partner: "industry",
  },
  {
    id: 6,
    name: "Sybert Stroeve",
    image: "../../assets/images/people/sybert-stroeve.png",
    companyLogo: "../../assets/images/consortium/nlr.png",
    institution: "nlr",
    role: "Scientist Safety & Human Performance",
    partner: "industry",
  },
];

export const institutions = [
  {
    id: 1,
    name: "Max Planck Institute",
    displayName: "MPI",
  },
  {
    id: 2,
    name: "TU/e Eindhoven University of Technology",
    displayName: "TU/e",
  },
  {
    id: 3,
    name: "KTH Royal Institute of Technology",
    displayName: "KTH",
  },
  {
    id: 4,
    name: "Uppsala University",
    displayName: "UU",
  },
  {
    id: 5,
    name: "Siemens",
    displayName: "Siemens",
  },
  {
    id: 6,
    name: "NLR - Royal Netherlands Aerospace Centre",
    displayName: "NLR",
  },
];
