export const members = [
    // {
    //     name: "",
    //     image: "../../assets/images/people/",
    //     description: " ",
    //     institution: "",
    //     role: "",
    //     partner: "",
    // },
    {
        name: 'Igo Besselink',
        image: '../../assets/images/people/igo-besselink.jpg',
        description: 'Associate Professor',
        institution: 'tu/e',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Didem Gürdür Broo',
        image: '../../assets/images/people/didem-gurdur-broo.png',
        description: 'Assistant Professor',
        institution: 'uu',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Arabinda Ghosh',
        image: '../../assets/images/people/arabinda-ghosh.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'MPI-SWS',
        role: 'phd',
        partner: 'academic',
        lab_link: 'https://sites.google.com/view/arabindaghosh',
    },
    {
        name: 'Arash Bahari Kordabad',
        image: '../../assets/images/people/arash-bahari-kordabad.png',
        description: 'Postdoctoral Researcher',
        institution: 'MPI-SWS',
        role: 'phd',
        partner: 'academic',
        lab_link: 'https://arashbaharik.github.io/',
    },
    {
        name: 'Kevin Tom  Kurian',
        image: '../../assets/images/people/kevin-tom-kurian.jpg',
        description: 'PhD Student',
        institution: 'tu/e',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Erjen Lefeber',
        image: '../../assets/images/people/erjen-lefeber.jpg',
        description: 'Assistant Professor',
        institution: 'tu/e',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Siyuan Liu',
        image: '../../assets/images/people/siyuan-liu.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'kth',
        role: 'phd',
        partner: 'academic',
        lab_link: 'https://si-yuan-liu.github.io/',
    },
    {
        name: 'Lars Lindemann',
        image: '../../assets/images/people/lars-lindemann.jpg',
        description: 'Assistant Professor',
        institution: 'kth',
        role: '',
        partner: 'affiliated',
    },
    {
        name: 'Gregorio Marchesini',
        image: '../../assets/images/people/gregorio-marchesini.png',
        description: 'PhD Student',
        institution: 'kth',
        role: 'phd',
        partner: 'academic',
        lab_link: 'https://www.kth.se/profile/gremar',
    },
    {
        name: 'Maryam Sharifi',
        image: '../../assets/images/people/maryam-sharifi.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'kth',
        role: '',
        partner: 'academic',
    },
    {
        name: 'Ana Tanevska',
        image: '../../assets/images/people/ana-tanevska.png',
        description: 'Postdoctoral Researcher',
        institution: 'uu',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Lefteris Vlahakis',
        image: '../../assets/images/people/lefteris-vlahakis.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'kth',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Ruohan Wang',
        image: '../../assets/images/people/ruohan-wang.jpg',
        description: 'PhD Student',
        institution: 'tu/e',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Katie Winkle',
        image: '../../assets/images/people/katie-winkle.png',
        description: 'Assistant Professor',
        institution: 'uu',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Zengjie Zhang',
        image: '../../assets/images/people/zengjie-zhang.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'tu/e',
        role: 'phd',
        partner: 'affiliated',
    },
    {
        name: 'Edwin Van Hassel',
        image: '../../assets/images/people/edwin-van-hassel.jpg',
        description: 'Principal Engineer',
        institution: 'siemens',
        role: '',
        partner: 'industry',
    },
    {
        name: 'Patrick Jonk',
        image: '../../assets/images/people/patrick-jonk.jfif',
        description: 'R&D Engineer',
        institution: 'nlr',
        role: 'phd',
        partner: 'industry',
    },
    {
        name: 'Ernesto Casablanca',
        image: '../../assets/images/people/ernesto-casablanca.jpg',
        description: 'PhD Student',
        institution: 'MPI-SWS',
        role: 'phd',
        partner: 'academic',
        lab_link: 'https://tendto.github.io/en/',
    },
    {
        name: 'Natalia Calvo-Barajas',
        image: '../../assets/images/people/natalia-calvo-barajas.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'UU',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Ronald Cumbal',
        image: '../../assets/images/people/ronald-cumbal.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'UU',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Alexandros Rouchitsas',
        image: '../../assets/images/people/alexandros-rouchitsas.jpg',
        description: 'Postdoctoral Researcher',
        institution: 'UU',
        role: 'phd',
        partner: 'academic',
    },
    {
        name: 'Birgit Van Huijgevoort',
        image: '../../assets/images/people/birgit-van-huijgevoort.jpg',
        description: ' Teacher and Researcher',
        institution: 'Avans',
        role: 'phd',
        partner: 'affiliated',
    },
]

export const leaders = [
    // {
    //     name: "",
    //     image: "",
    //     companyLogo: "",
    // },
    {
        id: 1,
        name: 'Dr. Sadegh Soudjani',
        image: '../../assets/images/people/sadegh-soudjani.png',
        companyLogo: '../../assets/images/consortium/MPI-SWS.png',
        institution: 'MPI-SWS',
        role: 'Project Coordinator & Principal Investigator',
        partner: 'academic',
        lab_link: 'https://hycodev.com',
    },
    {
        id: 4,
        name: 'Prof. Ginevra Castellano',
        image: '../../assets/images/people/ginevra-castellano.png',
        companyLogo: '../../assets/images/consortium/uu.png',
        institution: 'uu',
        role: 'Principal Investigator',
        partner: 'academic',
        lab_link: 'https://usr-lab.github.io',
    },
    {
        id: 3,
        name: 'Prof. Dimos Dimarogonas',
        image: '../../assets/images/people/dimos-dimarogonas.png',
        companyLogo: '../../assets/images/consortium/kth.png',
        institution: 'kth',
        role: 'Principal Investigator',
        partner: 'academic',
        lab_link: 'https://people.kth.se/~dimos/',
    },
    {
        id: 2,
        name: 'Dr. Sofie Haesaert',
        image: '../../assets/images/people/sofie-haesaert.png',
        companyLogo: '../../assets/images/consortium/tue.png',
        institution: 'tu/e',
        role: 'Principal Investigator',
        partner: 'academic',
        lab_link:
            'https://www.tue.nl/en/research/research-groups/control-systems',
    },
    {
        id: 6,
        name: 'Dr. Mohsen Alirezaei',
        image: '../../assets/images/people/mohsen-allrezael.png',
        companyLogo: '../../assets/images/consortium/siemens.png',
        institution: 'siemens',
        role: 'Principal Investigator',
        partner: 'industry',
        lab_link:
            'https://plm.sw.siemens.com/en-US/simcenter/autonomous-vehicle-solutions',
    },
    {
        id: 5,
        name: 'Dr. Sybert Stroeve',
        image: '../../assets/images/people/sybert-stroeve.png',
        companyLogo: '../../assets/images/consortium/nlr.png',
        institution: 'nlr',
        role: 'Principal Investigator',
        partner: 'industry',
        lab_link: 'https://www.nlr.org/',
    },
]

export const institutions = [
    {
        id: 1,
        name: 'Max Planck Institute',
        displayName: 'MPI-SWS',
    },
    {
        id: 3,
        name: 'KTH Royal Institute of Technology',
        displayName: 'KTH',
    },
    {
        id: 2,
        name: 'TU/e Eindhoven University of Technology',
        displayName: 'TU/e',
    },

    {
        id: 4,
        name: 'Uppsala University',
        displayName: 'UU',
    },
    {
        id: 6,
        name: 'NLR - Royal Netherlands Aerospace Centre',
        displayName: 'NLR',
    },
    {
        id: 5,
        name: 'Siemens',
        displayName: 'Siemens',
    },
    {
        id: 6,
        name: 'Avans University of Applied Sciences',
        displayName: 'Avans',
    },
]
