name: Build and Deploy (github pages)

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base-href=/symaware/

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/www.symaware.eu

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
