name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: chill-viking/npm-ci@latest
        name: Install npm dependencies

      - name: Build
        run: npm run build -- --base-href=/symaware/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/www.symaware.eu

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Push To Server
      #   uses: appleboy/scp-action@v1
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     source: dist/www.symaware.eu
      #     target: /www/sws-websites/
      #     strip_components: 1
      #     overwrite: true
